version: '2'
catalog:
  name: zy-thirdparty-data
  version: 1.0.6-rancher1
  description: |
    (Experimental) zy-thirdparty-data.
  minimum_rancher_version: v1.0.0
  maintainer: "JML <9267435@qq.com>"
  uuid: zy-thirdparty-data-0
  questions:
    - variable: "scale"
      description: "副本数量"
      label: "scale:"
      required: true
      default: 1
      type: "int"
    - variable: "profile"
      description: "系统环境"
      label: "profile:"
      required: true
      default: rancher
      type: "string"
      
    - variable: "host_label"
      description: "host"
      label: "host_label:"
      required: true
      default: "server=true"
      type: "string"
    
    - variable: "docker_version"
      description: "镜像版本"
      label: "docker_version:"
      required: true
      default: "1.0"
      type: "string"
      
    - variable: "mysql_link"
      description: "数据库关联地址"
      label: "mysql_link:"
      required: false
      type: "service"

    - variable: "eurekaserver"
      description: "eurekaserver地址"
      label: "eurekaserver:"
      required: true
      type: "service"
    
    - variable: "configserver"
      description: "configserver地址"
      label: "configserver:"
      required: true
      type: "service"

    - variable: "kafka_link"
      description: "kafka关联地址"
      label: "kafka_link:"
      required: false
      type: "service"
      

    - variable: "log_path"
      description: "日志路径"
      label: "log_path:"
      required: true
      type: "string"
      default: "/usr01/logs/zyservice"

    - variable: "JAVA_OPTS"
      description: "JAVA_OPTS"
      label: "JAVA_OPTS:"
      required: true
      type: "string"
      default: "-server -Xms1024m -Xmx1024m -XX:NewSize=320m -XX:MaxNewSize=320m -XX:PermSize=96m -XX:MaxPermSize=256m -Xmn500m -XX:MaxTenuringThreshold=5"
services:
  mox-service:
    scale: ${scale}
    start_on_create: true
  bairong-service:
    scale: ${scale}
    start_on_create: true
  car-service:
    scale: ${scale}
    start_on_create: true
  sms-service:
    scale: ${scale}
    start_on_create: true 
