version: '2'
catalog:
  name: zy-springcloud
  version: 1.0.6-rancher1
  description: |
    (Experimental) zy-springcloud.
  minimum_rancher_version: v1.0.0
  maintainer: "JML <9267435@qq.com>"
  uuid: zy-springcloud-0
  questions:
    - variable: "scale"
      description: "副本数量"
      label: "scale:"
      required: true
      default: 1
      type: "int"
    - variable: "profile"
      description: "系统环境"
      label: "profile:"
      required: true
      default: 1
      type: "string"
      
    - variable: "host_label"
      description: "host"
      label: "host_label:"
      required: true
      default: "server=true"
      type: "string"
    
    - variable: "docker_version"
      description: "镜像版本"
      label: "docker_version:"
      required: true
      default: "1.0.0"
      type: "string"
      
    - variable: "mysql_link"
      description: "数据库关联地址"
      label: "mysql_link:"
      required: false
      type: "service"

    - variable: "eureka_link"
      description: "eureka地址"
      label: "eureka_link:"
      required: false
      type: "service"
    
    - variable: "zookeeper_link"
      description: "zk关联地址"
      label: "zk_link:"
      required: false
      type: "service"
    
    - variable: "redis_link"
      description: "redis关联地址"
      label: "redis_link:"
      required: false
      type: "service"
      
    - variable: "kafka_link"
      description: "kafka关联地址"
      label: "kafka_link:"
      required: false
      type: "service"
      
    - variable: "mongodb_link"
      description: "mongodb关联地址"
      label: "mongodb_link:"
      required: false
      type: "service"
      
    - variable: "es_link"
      description: "es关联地址"
      label: "es_link:"
      required: false
      default: es/dev
      type: "service"
    
    - variable: "es_cluster_name"
      description: "es集群名"
      label: "es_cluster_name:"
      required: false
      default: es_cluster
      type: "string"
      
    - variable: "rabbitmq_link"
      description: "rabbitmq关联地址"
      label: "rabbitmq_link:"
      required: false
      type: "service"

    - variable: "log_path"
      description: "日志路径"
      label: "log_path:"
      required: true
      type: "string"
