version: '2'
services:
  dealer-service:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/dealer-service:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
  dealer-web:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/dealer-web:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
  erp-service:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/erp-service:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
  erp-web:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/erp-web:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
volumes:
  dealer-volume:
    driver: local
    per_container: true