version: '2'
services:
  cfservice:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: cfservice-volume , cfservice-log
    image: register.zytc.com/library/cfservice:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${eurekaserver}:eurekaserver
      - ${configserver}:configserver
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
      - ${eureka_link}:eurekaserver
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - cfservice-volume
  cfservice-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - eurekaserverdata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  cfservice-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:cfservice
    volumes_from:
    - cfservice-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

volumes:
  cfservicedata:
    driver: local
    per_container: true
