version: '2'
services:
  apollo-configservice:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/apollo-configservice:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
  apollo-adminservice:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/apollo-adminservice:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
  apollo-portal:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
    image: registry.cn-beijing.aliyuncs.com/jml/apollo-portal:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
volumes:
  config-volume:
    driver: local
    per_container: true