version: '2'
services:
  cfservice:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: cfservice-volume , cfservice-log
    image: register.zytc.com/library/cfservice:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
      - ${eureka_link}:eurekaserver
    links:
      - eurekaserver
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - cfservice-volume
  cfservice-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - eurekaserverdata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  cfservice-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:eurekaserver
    volumes_from:
    - eurekaserver-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  gateway:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: gateway-volume , gateway-log
    image: register.zytc.com/library/gateway:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
      - ${eureka_link}:eurekaserver
    links:
      - eurekaserver
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - gateway-volume
  gateway-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - gatewaydata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  gateway-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:eurekaserver
    volumes_from:
    - gateway-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  dataexservice:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: dataexservice-volume , dataexservice-log
    image: register.zytc.com/library/dataexservice:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
      - ${eureka_link}:eurekaserver
    environment:
      - ENV=${profile}
    links:
      - eurekaserver
    expose:
      - "8080"
    tty: true
    volumes_from:
    - dataexservice-volume
  dataexservice-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - dataexservicedata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  dataexservice-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:eurekaserver
    volumes_from:
    - dataexservice-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  mox-service:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: mox-service-volume , mox-service-log
    image: register.zytc.com/library/mox-service:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
      - ${eureka_link}:eurekaserver
    environment:
      - ENV=${profile}
    links:
      - eurekaserver
    expose:
      - "8080"
    tty: true
    volumes_from:
    - mox-service-volume
  mox-service-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - mox-servicedata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  mox-service-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:eurekaserver
    volumes_from:
    - mox-service-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  eurekaserver:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: eurekaserver-volume , eurekaserver-log
    image: register.zytc.com/library/eurekaserver:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - eurekaserver-volume
  eurekaserver-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - eurekaserverdata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  eurekaserver-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:eurekaserver
    volumes_from:
    - eurekaserver-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  car-service:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: car-service-volume , car-service-log
    image: register.zytc.com/library/car-service:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - car-service-volume
  car-service-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - eurekaserverdata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  car-service-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:car-service
    volumes_from:
    - car-service-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  sms-service:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: sms-service-volume , sms-service-log
    image: register.zytc.com/library/sms-service:${docker_version}
    external_links:
      - ${mysql_link}:db
      - ${zookeeper_link}:zk
      - ${redis_link}:redis
      - ${kafka_link}:kafka.zytc.com
      - ${mongodb_link}:mongodb
      - ${es_link}:es
      - ${rabbitmq_link}:rabbitmq
    environment:
      - ENV=${profile}
    expose:
      - "8080"
    tty: true
    volumes_from:
    - eurekaserver-volume
  sms-service-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: ${log_path}
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: none
    volumes:
    - eurekaserverdata:${log_path}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  sms-service-log:
    image: register.zytc.com/library/filebeat:1.0-release
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
    external_links:
    - ${kafka_link}:kafka.zytc.com
    network_mode: container:sms-service
    volumes_from:
    - sms-service-volume
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
volumes:
  eurekaserverdata:
    driver: local
    per_container: true
  mox-servicedata:
    driver: local
    per_container: true
  dataexservicedata:
    driver: local
    per_container: true
  cfservicedata:
    driver: local
    per_container: true
  gatewaydata:
    driver: local
    per_container: true
  carservicedata:
    driver: local
    per_container: true
  smsservicedata:
    driver: local
    per_container: true